### ISSUE TITLE
pidgin crash matrix_e2e_handle_sync_key_counts

### ISSUE THREAD

**Issue by axet** [matrix-org/purple-matrix#125] opened 2022-08-10 11:24 UTC
I can provide more details if requested.

```
Program terminated with signal SIGABRT, Aborted.

warning: Section `.reg-xstate/135700' in core file too small.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f2b2976bac0 (LWP 135700))]
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
        set = {__val = {1024, 139823410764768, 255, 7, 0, 4096, 99, 271, 4144, 64, 481036337409, 8, 0, 1, 476741369955, 511101108348}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007f2b2ca01546 in __GI_abort () at abort.c:79
        save_stage = 1

                  act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, sa_mask = {__val = {502, 139823410767296, 94646745415280, 502, 502, 0, 139823409377651, 65536, 139823410767296, 94646745415280, 502, 139823410750720, 139823415622064, 94646755033344, 139823409330183, 140734495838036}}, sa_flags = -1439452416, sa_restorer = 0x7fff4da1dc10}

                    sigs = {__val = {32, 49, 139823410767296, 139823410747648, 139823410767296, 1, 94646745415781, 139823409380185, 10, 139823409381315, 94646745415782, 3432, 139823410747648, 139823409385473, 502, 139823409385136}}
#2  0x00005614a8c2ed1c in sighandler (sig=<optimized out>) at ../../pidgin/gtkmain.c:183
        written = <optimized out>
#3  0x00007f2b2cbca200 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f2b2cd7a145 in purple_connection_get_protocol_data () at /lib/x86_64-linux-gnu/libpurple.so.0
#5  0x00007f2b20575def in matrix_e2e_handle_sync_key_counts (pc=0x4120796e61626c41, count_object=0x5614b2817ad0, force_send=0) at matrix-e2e.c:936
        need_to_send = 0
        valid_counts = 0
        conn = 0x5614b3784c30
        max_keys = 139823202955366
        to_create = 0
        __func__ = "matrix_e2e_handle_sync_key_counts"
#6  0x00007f2b20575fee in key_upload_callback
    (conn=0x5614aa3411f0, user_data=0x0, json_root=0x5614b2886d60, body=0x5614aa5ff9f0 "{\"one_time_key_counts\":{\"signed_curve25519\":50}}@", body_len=48, content_type=0x5614ac9d6b40 "application/json") at matrix-e2e.c:989
        top_object = 0x5614b3784c30
        key_counts = 0x5614b2817ad0
        __func__ = "key_upload_callback"
#7  0x00007f2b20571550 in matrix_api_complete
    (url_data=0x5614aa368100, user_data=0x5614aa367b50, ret_data=0x5614aa61eb60 "HTTP/1.1 200 OK\r\nDate: Wed, 10 Aug 2022 11:11:33 GMT\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nsynapse-trace-id: a85858e4242b4130\r\ncache-control: no-cache, n"..., ret_len=710, error_message=0x0) at matrix-api.c:341
        data = 0x5614aa367b50
        response_data = 0x5614ac41e270
        response_code = 200
        root = 0x5614b2886d60

```

second crash

```
Program terminated with signal SIGABRT, Aborted.

warning: Section `.reg-xstate/137028' in core file too small.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7faeec273ac0 (LWP 137028))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007faeef509546 in __GI_abort () at abort.c:79
#2  0x000055a953665d1c in sighandler (sig=<optimized out>) at ../../pidgin/gtkmain.c:183
#3  0x00007faeef6d2200 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007faee307ddf7 in matrix_e2e_handle_sync_key_counts (pc=0x7faeefc023f0 <destroy_closure_array>, count_object=0x55a9564ae6c0, force_send=0)
    at matrix-e2e.c:937
#5  0x00007faee307dfee in key_upload_callback
    (conn=0x55a955d1edf0, user_data=0x0, json_root=0x7faeb4007540, body=0x55a9566cbdc0 "{\"one_time_key_counts\":{\"signed_curve25519\":50}}㵳", body_len=48, content_type=0x55a95664c4a0 "application/json") at matrix-e2e.c:989
#6  0x00007faee3079550 in matrix_api_complete
    (url_data=0x55a955d87f70, user_data=0x55a955d70860, ret_data=0x55a955e560f0 "HTTP/1.1 200 OK\r\nDate: Wed, 10 Aug 2022 11:20:51 GMT\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nsynapse-trace-id: e942a2136eb56606\r\ncache-control: no-cache, n"..., ret_len=710, error_message=0x0) at matrix-api.c:341
#7  0x00007faeef8d7381 in  () at /lib/x86_64-linux-gnu/libpurple.so.0
#8  0x000055a95364b4b2 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x55a955d56b20) at ../../pidgin/gtkeventloop.c:73
#9  0x00007faeefb04eb4 in g_main_dispatch (context=0x55a95541d5c0) at ../../../glib/gmain.c:3417
#10 g_main_context_dispatch (context=context@entry=0x55a95541d5c0) at ../../../glib/gmain.c:4135
#11 0x00007faeefb05258 in g_main_context_iterate (context=0x55a95541d5c0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4211
#12 0x00007faeefb05543 in g_main_loop_run (loop=0x55a955d20430) at ../../../glib/gmain.c:4411
#13 0x00007faef0207b2a in gtk_main () at /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#14 0x000055a95360ed7c in main (argc=<optimized out>, argv=<optimized out>) at ../../pidgin/gtkmain.c:948
```

one more

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at ./nptl/pthread_kill.c:44
#1  0x00007ff8855de89f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ff885592a52 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ff88557d469 in __GI_abort () at ./stdlib/abort.c:79
#4  0x000055f113988d1c in sighandler (sig=<optimized out>) at ../../pidgin/gtkmain.c:183
#5  0x00007ff885592af0 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#6  purple_connection_get_protocol_data (connection=0x55f44a512217) at ../../libpurple/connection.c:475
#7  0x00007ff881c708c9 in matrix_e2e_handle_sync_key_counts (pc=0x55f44a512217, count_object=0x55f1163d1cf0, force_send=0)
    at matrix-e2e.c:936
#8  0x00007ff881c70ac8 in key_upload_callback
    (conn=0x55f1153b7f20, user_data=0x0, json_root=0x55f1216a5c60, body=0x55f118d92600 "{\"one_time_key_counts\":{\"signed_curve25519\":96}}", body_len=48, content_type=0x55f119372a30 "application/json") at matrix-e2e.c:989
#9  0x00007ff881c6bbc7 in matrix_api_complete
    (url_data=0x55f11540d1c0, user_data=0x55f11540d180, ret_data=0x55f115431750 "HTTP/1.1 200 OK\r\nDate: Thu, 18 Aug 2022 11:04:10 GMT\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nsynapse-trace-id: 8e92c83b0e647e9f\r\ncache-control: no-cache, n"..., ret_len=760, error_message=0x0) at matrix-api.c:434
#10 0x00007ff8858e9381 in url_fetch_recv_cb (url_data=0x55f11540d1c0, source=<optimized out>, cond=<optimized out>)
    at ../../libpurple/util.c:4058
#11 0x000055f11396e4b2 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x55f1154074e0)
    at ../../pidgin/gtkeventloop.c:73
#12 0x00007ff885b16a9f in g_main_dispatch (context=0x55f114a755c0) at ../../../glib/gmain.c:3417
#13 g_main_context_dispatch (context=context@entry=0x55f114a755c0) at ../../../glib/gmain.c:4135
#14 0x00007ff885b16e58 in g_main_context_iterate
    (context=0x55f114a755c0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4211
#15 0x00007ff885b1710f in g_main_loop_run (loop=0x55f11532fb80) at ../../../glib/gmain.c:4411
#16 0x00007ff886217b2a in gtk_main () at /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#17 0x000055f113931d7c in main (argc=<optimized out>, argv=<optimized out>) at ../../pidgin/gtkmain.c:948
```

**Comment by axet** [comment] 2022-08-16 14:09
no longer crashing. i guess this can be memory corruption or using freed pointer.

**Comment by richvdh** [comment] 2022-08-19 09:59
Duplicate of #95

**Closed by richvdh** 2022-08-19 09:59 UTC

**Comment by penguin42** [comment] 2022-08-21 18:41
I'd be surprised if this one has really disappeared; but I think it only happens when olm gets new keys *and* the matrix server connection dies during uploading new keys.     If you retry and it succeeds things work for quite a while until that situation happens again.
(It's not clear if this happens because we do something bad when uploading new keys, e.g. reuploading the same keys because we thought it failed last time?)
