### ISSUE TITLE
 Matrix rooms will not Enumerate in Pidgin's XMPP Service Discovery.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [matrix-org/purple-matrix#122] opened 2021-12-10 03:05 UTC
Matrix rooms will not Enumerate in Pidgin's XMPP Service Discovery. This makes Matrix useless in Spectrum2.
I see no Rooms enumerated as XMPP Rooms, and I see no Matrix Contacts in Spectrum2.

**Comment by richvdh** [comment] 2023-03-13 13:09
duplicate of #138

**Closed by richvdh** 2023-03-13 13:09 UTC
